const images = {
  developer: require("./hero-1.webp"),
  hand: require("./waving-hand.webp"),
  html: require("./html-5.webp"),
  css: require("./css-3.webp"),
  sass: require("./sass.webp"),
  js: require("./js.webp"),
  python: require("./python.webp"),
  cpp: require("./c-.webp"),
  php: require("./php.webp"),
  sql: require("./mysql.webp"),
  mongodb: require("./mongodb.webp"),
  github: require("./github-day.webp"),
  bootstrap: require("./bootstrap.webp"),
  tailwind: require("./tailwind.webp"),
  react: require("./react.webp"),
  wave: require("./wave.webp"),
  proCab: require("./pro-cab.webp"),
  proQuote: require("./pro-quote.webp"),
  ham: require("./ham.webp"),
  close: require("./cross.webp"),
  weather: require("./pro-weather.webp"),
  profile: require("./profile.webp"),
  edu: require("./edu.webp"),
  resume: require("./resume.pdf"),
  lawyeric: require("./pro-lawyeric.webp"),
  postman: require("./postman.webp"),
  vscode: require("./vsCode.webp"),
  java: require("./java.webp"),
  cursor: require("./feather.png")
};
export default images;
